name: Build Worklog App Linux/Mac

on:
  push:
    tags:
      - 'v*.*.*'  # Only run on version tags like v1.0.0

jobs:
  build:
    name: Build on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]
        go-version: ['1.22.3']
        goos: [linux, darwin]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    # Install dependencies for CGO (SQLite)
    - name: Install dependencies on Linux
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y gcc libc6-dev

    - name: Install dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install gcc sqlite

    - name: Install global deps
      run: | 
      go get .
      go get github.com/mattn/go-sqlite3@v1.14.24

    - name: Build for Linux/macOS
      run: |
        GOOS=${{ matrix.goos }}
        GOARCH=${{ matrix.arch }}
        VERSION=${{ github.ref_name }}
        GIT_COMMIT := $(shell git rev-parse --short HEAD)
        export CGO_ENABLED=1 
        go build -ldflags "-X main.version=$(VERSION) -X main.gitCommit=$(GIT_COMMIT)" -o worklog-$GOOS-$GOARCH-$VERSION

    - name: Build for Windows
      run: | 

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: worklog-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}
        path: worklog-*
