name: Build and Release Worklog App Windows

on:
  push:
    tags:
      - 'v*.*.*'  # Only run on version tags like v1.0.0

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.3'

    - name: Install go deps
      run: go get .

    - name: Install global deps
      run: go get github.com/mattn/go-sqlite3@v1.14.24

    - name: Build
      run: |
        set VERSION=${{ github.ref_name }}
        set CGO_ENABLED=1
        .\build.bat

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: worklog-windows-amd64-${{ github.ref_name }}
        path: worklog-*

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}  # Use the tag version from the pushed tag
        name: Release ${{ github.ref_name }}
        body: |
          Release notes for version ${{ github.ref_name }}.
          - Windows binary attached.
        draft: true  # Set this to true to create a draft release
        files: worklog-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provided automatically by GitHub Actions

        # Upload artifact created in the build step to the release
