name: Build and Release Worklog App Windows

on:
  push:
    tags:
      - 'v*.*.*'  # Only run on version tags like v1.0.0

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        arch: ['amd64', 'arm64']
        go-version: ['1.22.3']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.3'

    # Install dependencies for CGO (SQLite)
    - name: Install dependencies on Linux
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y gcc libc6-dev

    - name: Install dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install gcc sqlite

    - name: Install global deps
      run: |
        go get .
        go get github.com/mattn/go-sqlite3@v1.14.24

    - name: Get Git Short Hash
      run: echo "GIT_SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        GOOS=linux
        GOARCH=${{ matrix.arch }}
        VERSION=${{ github.ref_name }}
        export CGO_ENABLED=1 
        go build -ldflags "-X main.version=${{ env.VERSION }} -X main.gitCommit=${{ env.GIT_SHORT_HASH }}" -o worklog-$GOOS-$GOARCH-$VERSION

    - name: Build for macOS
      if: matrix.os == 'macos-latest'
      run: |
        GOOS=darwin
        GOARCH=${{ matrix.arch }}
        VERSION=${{ github.ref_name }}
        GIT_COMMIT=$(git rev-parse --short HEAD)
        export CGO_ENABLED=1 
        go build -ldflags "-X main.version=${{ env.VERSION }} -X main.gitCommit=${{ env.GIT_SHORT_HASH }}" -o worklog-$GOOS-$GOARCH-$VERSION

    - name: Build for Windows
      if: matrix.os == 'windows-latest'
      run: |
        set VERSION=${{ github.ref_name }}
        set CGO_ENABLED=1
        .\build.bat windows ${{ matrix.arch }}

    - name: Upload Windows Binary
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: worklog-windows-${{ matrix.arch }}-${{ github.ref_name }}
        path: worklog-*

    - name: Upload macOS Binary
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: worklog-darwin-${{ matrix.arch }}-${{ github.ref_name }}
    
        path: worklog-*

    - name: Upload Linux Binary
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: worklog-linux-${{ matrix.arch }}-${{ github.ref_name }}
        path: worklog-*

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}  # Use the tag version from the pushed tag
        name: Release ${{ github.ref_name }}
        body: |
          Release notes for version ${{ github.ref_name }}.
          - Windows binary attached.
        draft: true  # Set this to true to create a draft release
        files: worklog-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provided automatically by GitHub Actions

        # Upload artifact created in the build step to the release
