name: Build Worklog App

on:
  push:
    tags:
      - 'v*.*.*'  # Only run on version tags like v1.0.0

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.3'

    - name: Install deps
      run: | 
      go get github.com/mattn/go-sqlite3@v1.14.24

    - name: Build
      run: |
        VERSION=${{ github.ref_name }}
        set CGO_ENABLED=1
        .\build.bat


    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: worklog-windows-amd64-${{ github.ref_name }}
        path: worklog-*
